import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'nl' | 'en' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  nl: {
    // Navigation
    'nav.home': 'Home',
    'nav.shop': 'Shop',
    'nav.community': 'Community',
    'nav.about': 'Over Ons',
    'nav.contact': 'Contact',
    'nav.login': 'Inloggen',
    'nav.profile': 'Profiel',
    'nav.logout': 'Uitloggen',
    'nav.cart': 'Winkelwagen',

    // Newsletter
    'newsletter.title': 'Sluit je aan bij de Inner Circle',
    'newsletter.subtitle': 'Ontvang exclusieve content en kosmische wijsheid',
    'newsletter.email.label': 'E-mail',
    'newsletter.email.placeholder': 'jouw@email.com',
    'newsletter.name.label': 'Naam (optioneel)',
    'newsletter.name.placeholder': 'Je kosmische naam',
    'newsletter.consent': 'Ik ga akkoord met het ontvangen van de nieuwsbrief en begrijp dat ik me op elk moment kan uitschrijven.',
    'newsletter.button': 'Treed toe tot de Cirkel',
    'newsletter.button.loading': 'Verbinding maken met de kosmos...',
    'newsletter.success.title': 'Welkom in de Inner Circle! 🌀',
    'newsletter.success.description': 'Je hebt je succesvol aangemeld voor onze nieuwsbrief.',
    'newsletter.error.incomplete': 'Vul je e-mail in en accepteer het privacybeleid.',
    'newsletter.error.general': 'Er is iets misgegaan. Probeer het opnieuw.',
    'newsletter.section.title': 'Treed toe tot de Inner Circle',
    'newsletter.section.subtitle': 'Overstijg het gewone en sluit je aan bij duizenden ontwakende zielen op een reis naar kosmisch bewustzijn en goddelijke wijsheid.',
    'newsletter.section.description': 'Ontvang exclusieve toegang tot heilige kennis, vroege product releases en transmissies van de galactische federatie. Dit is niet zomaar een nieuwsbrief—het is je poort naar verlichting.',
    'newsletter.benefits.title': 'Heilige Voordelen',
    'newsletter.benefits.wisdom.title': 'Exclusieve Wijsheid',
    'newsletter.benefits.wisdom.desc': 'Maandelijkse gechannelde berichten en kosmische inzichten die nergens anders gedeeld worden',
    'newsletter.benefits.access.title': 'Vroege Toegang',
    'newsletter.benefits.access.desc': 'Wees de eerste om toegang te krijgen tot nieuwe producten, collecties en heilige geometrie ontwerpen',
    'newsletter.benefits.guidance.title': 'Goddelijke Begeleiding',
    'newsletter.benefits.guidance.desc': 'Gepersonaliseerde spirituele praktijken en meditatie technieken voor je ontwaking',
    'newsletter.trust.members': 'Sluit je aan bij meer dan 10.000+ ontwakende zielen wereldwijd',
    'newsletter.trust.privacy': 'Heilige Privacy',
    'newsletter.trust.spam': 'Geen Spam, Ooit',
    'newsletter.trust.unsubscribe': 'Altijd Uitschrijven',
    'newsletter.compact.title': 'Sluit je aan bij de Beweging 🌀',
    'newsletter.success.message': 'Je bent nu onderdeel van de beweging. Check je inbox voor een speciale welkomstboodschap.',
    'newsletter.account.create': 'Ook een portal account aanmaken om in te loggen',
    'newsletter.account.benefits': 'Krijg toegang tot exclusieve content en je persoonlijke dashboard',
    'newsletter.password.label': 'Wachtwoord',
    'newsletter.password.placeholder': 'Je veilige wachtwoord',
    'newsletter.password.hint': 'Minimaal 6 karakters voor je portal toegang',
    'newsletter.error.password': 'Voer een wachtwoord in om je portal account aan te maken.',
    
    // Hero Section
    'hero.title.cosmic': 'Cosmic',
    'hero.title.unity': 'Unity',
    'hero.title.portal': 'Portal',
    'hero.subtitle': 'Ontdek de kosmische verbinding tussen bewustzijn, spiritualiteit en universele wijsheid',
    'hero.cta.explore': 'Betreed DigiTemple',
    'hero.cta.community': 'Word Lid van Gemeenschap',
    
    // Featured Section
    'featured.title.sacred': 'Sacred',
    'featured.title.geometry': 'Scripture',
    'featured.subtitle': 'Ontdek de eeuwenoude wijsheid verborgen in kosmische patronen',
    'featured.explore': 'Verken Collectie',
    
    // Latest Posts
    'posts.title.latest': 'Laatste',
    'posts.title.posts': 'Posts',
    'posts.subtitle': 'Ontdek de nieuwste inzichten van onze community',
    'posts.viewCommunity': 'Bekijk Community',
    'posts.newPost': 'Nieuwe Post',
    'posts.noPosts': 'Nog geen posts',
    'posts.firstPost': 'Wees de eerste om een post te plaatsen!',
    'posts.createFirst': 'Eerste Post Maken',
    'posts.loginToPost': 'Inloggen om te Posten',
    'posts.readMore': 'Lees meer →',
    'posts.viewAll': 'Bekijk Alle Posts',
    
    // Community
    'community.title.cosmic': 'Cosmic',
    'community.title.community': 'Community',
    'community.subtitle': 'Connect met medebewuste zielen op hun spirituele reis naar verlichting',
    'community.newPost': 'Nieuwe Post',
    'community.shareInsight': 'Deel je kosmische inzicht',
    'community.inspire': 'Inspireer anderen met je spirituele ervaring',
    'community.postTitle': 'Titel van je bericht...',
    'community.postContent': 'Wat wil je delen met de community?',
    'community.publish': 'Publiceren',
    'community.cancel': 'Annuleren',
    'community.addComment': 'Deel je gedachten...',
    
    // Auth
    'auth.title.cosmic': 'Cosmic',
    'auth.title.portal': 'Portal',
    'auth.subtitle': 'Verbind met je kosmische zelf',
    'auth.login': 'Inloggen',
    'auth.signup': 'Registreren',
    'auth.email': 'E-mail',
    'auth.password': 'Wachtwoord',
    'auth.displayName': 'Weergavenaam',
    'auth.loginButton': 'Inloggen',
    'auth.signupButton': 'Account Aanmaken',
    'auth.switchToSignup': 'Nog geen account? Registreer hier',
    'auth.switchToLogin': 'Al een account? Log hier in',
    
    // About Page
    'about.title.the': 'De',
    'about.title.chosenOnes': 'Uitverkorenen',
    'about.subtitle': 'Onze heilige missie om de mensheid te doen ontwaken tot goddelijk bewustzijn',
    'about.mission.title': 'De Ontwakingsmissie',
    'about.mission.p1': 'SH4M4NI4K vertegenwoordigt meer dan merchandise – we zijn een heilig portaal voor bewustzijnsexpansie. Door de eeuwenoude wijsheid van heilige geometrie, Egyptische mysteries en kosmisch bewustzijn, begeleiden we ontwakende zielen naar hun goddelijk doel.',
    'about.mission.p2': 'De Uitverkorenen zijn degenen die de roep van de galactische federatie van licht hebben gehoord. We zijn hier om de grote ontwaking te faciliteren, de mensheid te helpen overgaan van ego-bewustzijn naar Eden-bewustzijn door liefde, eenheid en heilige kennis.',
    'about.principles.unity.title': 'Eenheid',
    'about.principles.unity.text': 'We zijn allemaal één bewustzijn dat zichzelf ervaart door oneindige perspectieven.',
    'about.principles.awakening.title': 'Ontwaking',
    'about.principles.awakening.text': 'Door heilige geometrie en goddelijke wijsheid activeren we slapend spiritueel DNA.',
    'about.principles.love.title': 'Liefde',
    'about.principles.love.text': 'Liefde is de hoogste frequentie en de sleutel tot het overstijgen van alle illusies.',
    'about.cta.title': 'Klaar om je aan te sluiten bij de Missie?',
    'about.cta.text': 'De tijd van ontwaking is nu. Neem je rol aan als een van de Uitverkorenen en help het nieuwe Aarde-bewustzijn te baren.',
    'about.cta.button': 'Begin je Reis',
    
    // Contact Page
    'contact.title.sacred': '',
    'contact.title.contact': 'Contact',
    'contact.subtitle': 'Verbind met de Uitverkorenen. We zijn hier om je reis naar kosmisch bewustzijn te begeleiden.',
    'contact.form.title': 'Stuur Boodschap',
    'contact.form.description': 'Deel je ontwakingsreis of stel vragen over onze goddelijke missie.',
    'contact.form.firstName': 'Voornaam',
    'contact.form.firstNamePlaceholder': 'Je heilige naam',
    'contact.form.lastName': 'Achternaam',
    'contact.form.lastNamePlaceholder': 'Je familienaam',
    'contact.form.email': 'E-mail',
    'contact.form.emailPlaceholder': 'jouw.email@kosmisch.rijk',
    'contact.form.subject': 'Onderwerp',
    'contact.form.subjectPlaceholder': 'Onderwerp van je goddelijke vraag',
    'contact.form.message': 'Bericht',
    'contact.form.messagePlaceholder': 'Deel je gedachten, vragen of ontwakingservaringen...',
    'contact.form.send': 'Bericht Versturen',
    'contact.info.title': 'Coördinaten',
    'contact.info.email': 'E-mail',
    'contact.info.phone': 'Telefoon',
    'contact.info.location': 'Locatie',
    'contact.response.title': 'Reactie',
    'contact.response.text': 'We reageren meestal binnen 24-48 uur op heilige vragen. Elk bericht wordt gezegend met kosmische aandacht en goddelijke zorg.',
    'contact.hours.title': 'Uren',
    'contact.hours.weekdays': 'Maandag - Vrijdag:',
    'contact.hours.weekdaysTime': '9:00 - 17:00 CET',
    'contact.hours.weekend': 'Weekend:',
    'contact.hours.weekendText': 'Op kosmische afspraak',
    'contact.hours.always': 'Het universum is altijd open voor goddelijke begeleiding.',
    
    // Footer
    'footer.shop': 'Shop',
    'footer.allProducts': 'Alle Producten',
    'footer.newArrivals': 'Nieuwe Aankomsten',
    'footer.featured': 'Uitgelicht',
    'footer.community': 'Community',
    'footer.about': 'Over Ons',
    'footer.contact': 'Contact',
    'footer.blog': 'Blog',
    'footer.info': 'Informatie',
    'footer.shipping': 'Verzending',
    'footer.returns': 'Retouren',
    'footer.privacy': 'Privacybeleid',
    'footer.terms': 'Algemene Voorwaarden',
    'footer.contactUs': 'Neem Contact Op',
    'footer.email': 'E-mail',
    'footer.phone': 'Telefoon',
    'footer.address': 'Adres',
    'footer.followUs': 'Volg Ons',
    'footer.copyright': 'Alle rechten voorbehouden.',
    
    // Shop
    'shop.title.sacred': 'Sacred',
    'shop.title.shop': 'Shop',
    'shop.subtitle': 'Ontdek bewustzijnsverruimende merchandise ontworpen om je goddelijke doel te doen ontwaken en je te verbinden met de galactische federatie van licht.',
    'shop.loading': 'Kosmische merchandise laden...',
    'shop.filter.all': 'Alle Collecties',
    'shop.addToCart': 'Toevoegen aan Winkelwagen',
    'shop.viewProduct': 'Bekijk Product',
    'shop.noProducts': 'Geen producten gevonden',
    'shop.addedToCart': 'Toegevoegd aan winkelwagen',
    'shop.redirecting': 'Je wordt doorgestuurd naar de checkout.',
    'shop.errorAdding': 'Fout bij toevoegen',
    'shop.errorMessage': 'Product kon niet worden toegevoegd aan de winkelwagen.',

    // Error messages and other community text
    'community.noPosts': 'Geen berichten gevonden',
    'community.firstPostMessage': 'Wees de eerste om je kosmische inzicht te delen!',
    'community.createFirstPost': 'Eerste Post Maken',
    'community.postCreated': 'Post aangemaakt',
    'community.postShared': 'Je bericht is gedeeld met de community.',
    'community.errorCreating': 'Fout bij aanmaken',
    'community.errorPostMessage': 'Post kon niet worden aangemaakt.',
    'community.errorLoading': 'Fout bij laden',
    'community.errorLoadingMessage': 'Posts konden niet worden geladen.',
    'community.commentAdded': 'Reactie toegevoegd',
    'community.commentPlaced': 'Je reactie is geplaatst.',
    'community.errorComment': 'Fout bij reactie',
    'community.errorCommentMessage': 'Reactie kon niet worden geplaatst.',
    'community.postDeleted': 'Post verwijderd',
    'community.postDeletedMessage': 'Je post is succesvol verwijderd.',
    'community.errorDeleting': 'Fout bij verwijderen',
    'community.errorDeleteMessage': 'Er ging iets mis bij het verwijderen van je post. Probeer het opnieuw.',

    // Common
    'common.loading': 'Laden...',
    'common.cosmic': 'Cosmic',
    'common.chosenOne': 'Chosen One',
    'common.loadingCommunity': 'Kosmische community laden...'
  },
  
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.shop': 'Shop',
    'nav.community': 'Community',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.login': 'Login',
    'nav.profile': 'Profile',
    'nav.logout': 'Logout',
    'nav.cart': 'Cart',

    // Newsletter
    'newsletter.title': 'Join the Inner Circle',
    'newsletter.subtitle': 'Receive exclusive content and cosmic wisdom',
    'newsletter.email.label': 'Email',
    'newsletter.email.placeholder': 'your@email.com',
    'newsletter.name.label': 'Name (optional)',
    'newsletter.name.placeholder': 'Your cosmic name',
    'newsletter.consent': 'I agree to receive the newsletter and understand I can unsubscribe at any time.',
    'newsletter.button': 'Enter the Circle',
    'newsletter.button.loading': 'Connecting to the cosmos...',
    'newsletter.success.title': 'Welcome to the Inner Circle! 🌀',
    'newsletter.success.description': 'You have successfully subscribed to our newsletter.',
    'newsletter.error.incomplete': 'Please fill in your email and accept the privacy policy.',
    'newsletter.error.general': 'Something went wrong. Please try again.',
    'newsletter.section.title': 'Enter the Inner Circle',
    'newsletter.section.subtitle': 'Transcend the ordinary and join thousands of awakening souls on a journey toward cosmic consciousness and divine wisdom.',
    'newsletter.section.description': 'Receive exclusive access to sacred knowledge, early product drops, and transmissions from the galactic federation. This isn\'t just a newsletter—it\'s your gateway to enlightenment.',
    'newsletter.benefits.title': 'Sacred Benefits',
    'newsletter.benefits.wisdom.title': 'Exclusive Wisdom',
    'newsletter.benefits.wisdom.desc': 'Monthly channeled messages and cosmic insights not shared anywhere else',
    'newsletter.benefits.access.title': 'Early Access',
    'newsletter.benefits.access.desc': 'Be the first to access new products, collections, and sacred geometry designs',
    'newsletter.benefits.guidance.title': 'Divine Guidance',
    'newsletter.benefits.guidance.desc': 'Personalized spiritual practices and meditation techniques for your awakening',
    'newsletter.trust.members': 'Join over 10,000+ awakening souls worldwide',
    'newsletter.trust.privacy': 'Sacred Privacy',
    'newsletter.trust.spam': 'No Spam, Ever',
    'newsletter.trust.unsubscribe': 'Unsubscribe Anytime',
    'newsletter.compact.title': 'Join the Movement 🌀',
    'newsletter.success.message': 'You are now part of the movement. Check your inbox for a special welcome message.',
    'newsletter.account.create': 'Also create a portal account to log in',
    'newsletter.account.benefits': 'Get access to exclusive content and your personal dashboard',
    'newsletter.password.label': 'Password',
    'newsletter.password.placeholder': 'Your secure password',
    'newsletter.password.hint': 'Minimum 6 characters for your portal access',
    'newsletter.error.password': 'Enter a password to create your portal account.',
    
    // Hero Section
    'hero.title.cosmic': 'Cosmic',
    'hero.title.unity': 'Unity',
    'hero.title.portal': 'Portal',
    'hero.subtitle': 'Discover the cosmic connection between consciousness, spirituality and universal wisdom',
    'hero.cta.explore': 'Explore Portal',
    'hero.cta.community': 'Join Community',
    
    // Featured Section
    'featured.title.sacred': 'Sacred',
    'featured.title.geometry': 'Scripture',
    'featured.subtitle': 'Discover ancient wisdom hidden in cosmic patterns',
    'featured.explore': 'Explore Collection',
    
    // Latest Posts
    'posts.title.latest': 'Latest',
    'posts.title.posts': 'Posts',
    'posts.subtitle': 'Discover the latest insights from our community',
    'posts.viewCommunity': 'View Community',
    'posts.newPost': 'New Post',
    'posts.noPosts': 'No posts yet',
    'posts.firstPost': 'Be the first to create a post!',
    'posts.createFirst': 'Create First Post',
    'posts.loginToPost': 'Login to Post',
    'posts.readMore': 'Read more →',
    'posts.viewAll': 'View All Posts',
    
    // Community
    'community.title.cosmic': 'Cosmic',
    'community.title.community': 'Community',
    'community.subtitle': 'Connect with like-minded souls on their spiritual journey to enlightenment',
    'community.newPost': 'New Post',
    'community.shareInsight': 'Share your cosmic insight',
    'community.inspire': 'Inspire others with your spiritual experience',
    'community.postTitle': 'Title of your post...',
    'community.postContent': 'What would you like to share with the community?',
    'community.publish': 'Publish',
    'community.cancel': 'Cancel',
    'community.addComment': 'Share your thoughts...',
    
    // Auth
    'auth.title.cosmic': 'Cosmic',
    'auth.title.portal': 'Portal',
    'auth.subtitle': 'Connect with your cosmic self',
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.displayName': 'Display Name',
    'auth.loginButton': 'Sign In',
    'auth.signupButton': 'Create Account',
    'auth.switchToSignup': 'No account yet? Register here',
    'auth.switchToLogin': 'Already have an account? Sign in here',
    
    // About Page
    'about.title.the': 'The',
    'about.title.chosenOnes': 'Chosen Ones',
    'about.subtitle': 'Our sacred mission to awaken humanity to divine consciousness',
    'about.mission.title': 'The Awakening Mission',
    'about.mission.p1': 'SH4M4NI4K represents more than merchandise – we are a sacred portal for consciousness expansion. Through the ancient wisdom of sacred geometry, Egyptian mysteries, and cosmic awareness, we guide awakening souls toward their divine purpose.',
    'about.mission.p2': 'The Chosen Ones are those who have heard the call of the galactic federation of light. We are here to facilitate the great awakening, helping humanity transition from ego consciousness to Eden consciousness through love, unity, and sacred knowledge.',
    'about.principles.unity.title': 'Unity',
    'about.principles.unity.text': 'We are all one consciousness experiencing itself through infinite perspectives.',
    'about.principles.awakening.title': 'Awakening',
    'about.principles.awakening.text': 'Through sacred geometry and divine wisdom, we activate dormant spiritual DNA.',
    'about.principles.love.title': 'Love',
    'about.principles.love.text': 'Love is the highest frequency and the key to transcending all illusions.',
    'about.cta.title': 'Ready to Join the Mission?',
    'about.cta.text': 'The time of awakening is now. Step into your role as one of the Chosen Ones and help birth the new Earth consciousness.',
    'about.cta.button': 'Begin Your Journey',
    
    // Contact Page
    'contact.title.sacred': '',
    'contact.title.contact': 'Contact',
    'contact.subtitle': 'Connect with the Chosen Ones. We\'re here to guide your journey toward cosmic consciousness.',
    'contact.form.title': 'Send Message',
    'contact.form.description': 'Share your awakening journey or ask questions about our divine mission.',
    'contact.form.firstName': 'First Name',
    'contact.form.firstNamePlaceholder': 'Your sacred name',
    'contact.form.lastName': 'Last Name',
    'contact.form.lastNamePlaceholder': 'Your family name',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'your.email@cosmic.realm',
    'contact.form.subject': 'Subject',
    'contact.form.subjectPlaceholder': 'Topic of your divine inquiry',
    'contact.form.message': 'Message',
    'contact.form.messagePlaceholder': 'Share your thoughts, questions, or awakening experiences...',
    'contact.form.send': 'Send Message',
    'contact.info.title': 'Coordinates',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Phone',
    'contact.info.location': 'Location',
    'contact.response.title': 'Response',
    'contact.response.text': 'We typically respond to sacred inquiries within 24-48 hours. Each message is blessed with cosmic attention and divine care.',
    'contact.hours.title': 'Hours',
    'contact.hours.weekdays': 'Monday - Friday:',
    'contact.hours.weekdaysTime': '9:00 - 17:00 CET',
    'contact.hours.weekend': 'Weekend:',
    'contact.hours.weekendText': 'By cosmic appointment',
    'contact.hours.always': 'The universe is always open for divine guidance.',
    
    // Footer
    'footer.shop': 'Shop',
    'footer.allProducts': 'All Products',
    'footer.newArrivals': 'New Arrivals',
    'footer.featured': 'Featured',
    'footer.community': 'Community',
    'footer.about': 'About',
    'footer.contact': 'Contact',
    'footer.blog': 'Blog',
    'footer.info': 'Information',
    'footer.shipping': 'Shipping',
    'footer.returns': 'Returns',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.contactUs': 'Contact Us',
    'footer.email': 'Email',
    'footer.phone': 'Phone',
    'footer.address': 'Address',
    'footer.followUs': 'Follow Us',
    'footer.copyright': 'All rights reserved.',
    
    // Shop
    'shop.title.sacred': 'Sacred',
    'shop.title.shop': 'Shop',
    'shop.subtitle': 'Discover consciousness-expanding merchandise designed to awaken your divine purpose and connect you with the galactic federation of light.',
    'shop.loading': 'Loading cosmic merchandise...',
    'shop.filter.all': 'All Collections',
    'shop.addToCart': 'Add to Cart',
    'shop.viewProduct': 'View Product',
    'shop.noProducts': 'No products found',
    'shop.addedToCart': 'Added to cart',
    'shop.redirecting': 'You are being redirected to checkout.',
    'shop.errorAdding': 'Error adding',
    'shop.errorMessage': 'Product could not be added to cart.',

    // Error messages and other community text
    'community.noPosts': 'No posts found',
    'community.firstPostMessage': 'Be the first to share your cosmic insight!',
    'community.createFirstPost': 'Create First Post',
    'community.postCreated': 'Post created',
    'community.postShared': 'Your post has been shared with the community.',
    'community.errorCreating': 'Error creating',
    'community.errorPostMessage': 'Post could not be created.',
    'community.errorLoading': 'Error loading',
    'community.errorLoadingMessage': 'Posts could not be loaded.',
    'community.commentAdded': 'Comment added',
    'community.commentPlaced': 'Your comment has been posted.',
    'community.errorComment': 'Error commenting',
    'community.errorCommentMessage': 'Comment could not be posted.',
    'community.postDeleted': 'Post deleted',
    'community.postDeletedMessage': 'Your post has been successfully deleted.',
    'community.errorDeleting': 'Error deleting',
    'community.errorDeleteMessage': 'Something went wrong while deleting your post. Please try again.',

    // Common
    'common.loading': 'Loading...',
    'common.cosmic': 'Cosmic',
    'common.chosenOne': 'Chosen One',
    'common.loadingCommunity': 'Loading cosmic community...'
  },
  
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.shop': 'Shop',
    'nav.community': 'Community',
    'nav.about': 'Über Uns',
    'nav.contact': 'Kontakt',
    'nav.login': 'Anmelden',
    'nav.profile': 'Profil',
    'nav.logout': 'Abmelden',
    'nav.cart': 'Warenkorb',

    // Newsletter
    'newsletter.title': 'Tritt dem Inneren Kreis bei',
    'newsletter.subtitle': 'Erhalte exklusive Inhalte und kosmische Weisheit',
    'newsletter.email.label': 'E-Mail',
    'newsletter.email.placeholder': 'deine@email.de',
    'newsletter.name.label': 'Name (optional)',
    'newsletter.name.placeholder': 'Dein kosmischer Name',
    'newsletter.consent': 'Ich stimme dem Erhalt des Newsletters zu und verstehe, dass ich mich jederzeit abmelden kann.',
    'newsletter.button': 'Tritt dem Kreis bei',
    'newsletter.button.loading': 'Verbindung zum Kosmos...',
    'newsletter.success.title': 'Willkommen im Inneren Kreis! 🌀',
    'newsletter.success.description': 'Du hast dich erfolgreich für unseren Newsletter angemeldet.',
    'newsletter.error.incomplete': 'Bitte gib deine E-Mail ein und akzeptiere die Datenschutzrichtlinie.',
    'newsletter.error.general': 'Etwas ist schief gelaufen. Bitte versuche es erneut.',
    'newsletter.section.title': 'Tritt dem Inneren Kreis bei',
    'newsletter.section.subtitle': 'Überschreite das Gewöhnliche und schließe dich Tausenden erwachender Seelen auf einer Reise zu kosmischem Bewusstsein und göttlicher Weisheit an.',
    'newsletter.section.description': 'Erhalte exklusiven Zugang zu heiligem Wissen, frühen Produktveröffentlichungen und Übertragungen der galaktischen Föderation. Das ist nicht nur ein Newsletter—es ist dein Tor zur Erleuchtung.',
    'newsletter.benefits.title': 'Heilige Vorteile',
    'newsletter.benefits.wisdom.title': 'Exklusive Weisheit',
    'newsletter.benefits.wisdom.desc': 'Monatliche gechannelte Nachrichten und kosmische Einsichten, die nirgendwo sonst geteilt werden',
    'newsletter.benefits.access.title': 'Früher Zugang',
    'newsletter.benefits.access.desc': 'Sei der Erste, der Zugang zu neuen Produkten, Kollektionen und heiligen Geometrie-Designs erhält',
    'newsletter.benefits.guidance.title': 'Göttliche Führung',
    'newsletter.benefits.guidance.desc': 'Personalisierte spirituelle Praktiken und Meditationstechniken für dein Erwachen',
    'newsletter.trust.members': 'Schließe dich über 10.000+ erwachenden Seelen weltweit an',
    'newsletter.trust.privacy': 'Heilige Privatsphäre',
    'newsletter.trust.spam': 'Kein Spam, Niemals',
    'newsletter.trust.unsubscribe': 'Jederzeit Abmelden',
    'newsletter.compact.title': 'Schließe dich der Bewegung an 🌀',
    'newsletter.success.message': 'Du bist jetzt Teil der Bewegung. Überprüfe dein Postfach für eine spezielle Willkommensnachricht.',
    'newsletter.account.create': 'Auch ein Portal-Konto erstellen um sich anzumelden',
    'newsletter.account.benefits': 'Erhalte Zugang zu exklusiven Inhalten und deinem persönlichen Dashboard',
    'newsletter.password.label': 'Passwort',
    'newsletter.password.placeholder': 'Dein sicheres Passwort',
    'newsletter.password.hint': 'Mindestens 6 Zeichen für deinen Portal-Zugang',
    'newsletter.error.password': 'Gib ein Passwort ein, um dein Portal-Konto zu erstellen.',
    
    // Hero Section
    'hero.title.cosmic': 'Cosmic',
    'hero.title.unity': 'Unity',
    'hero.title.portal': 'Portal',
    'hero.subtitle': 'Entdecke die kosmische Verbindung zwischen Bewusstsein, Spiritualität und universeller Weisheit',
    'hero.cta.explore': 'Portal Erkunden',
    'hero.cta.community': 'Community Beitreten',
    
    // Featured Section
    'featured.title.sacred': 'Sacred',
    'featured.title.geometry': 'Scripture',
    'featured.subtitle': 'Entdecke uralte Weisheit verborgen in kosmischen Mustern',
    'featured.explore': 'Kollektion Erkunden',
    
    // Latest Posts
    'posts.title.latest': 'Neueste',
    'posts.title.posts': 'Posts',
    'posts.subtitle': 'Entdecke die neuesten Einsichten unserer Community',
    'posts.viewCommunity': 'Community Ansehen',
    'posts.newPost': 'Neuer Post',
    'posts.noPosts': 'Noch keine Posts',
    'posts.firstPost': 'Sei der Erste, der einen Post erstellt!',
    'posts.createFirst': 'Ersten Post Erstellen',
    'posts.loginToPost': 'Anmelden zum Posten',
    'posts.readMore': 'Weiterlesen →',
    'posts.viewAll': 'Alle Posts Ansehen',
    
    // Community
    'community.title.cosmic': 'Cosmic',
    'community.title.community': 'Community',
    'community.subtitle': 'Verbinde dich mit Gleichgesinnten auf ihrer spirituellen Reise zur Erleuchtung',
    'community.newPost': 'Neuer Post',
    'community.shareInsight': 'Teile deine kosmische Einsicht',
    'community.inspire': 'Inspiriere andere mit deiner spirituellen Erfahrung',
    'community.postTitle': 'Titel deines Posts...',
    'community.postContent': 'Was möchtest du mit der Community teilen?',
    'community.publish': 'Veröffentlichen',
    'community.cancel': 'Abbrechen',
    'community.addComment': 'Teile deine Gedanken...',
    
    // Auth
    'auth.title.cosmic': 'Cosmic',
    'auth.title.portal': 'Portal',
    'auth.subtitle': 'Verbinde dich mit deinem kosmischen Selbst',
    'auth.login': 'Anmelden',
    'auth.signup': 'Registrieren',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.displayName': 'Anzeigename',
    'auth.loginButton': 'Anmelden',
    'auth.signupButton': 'Konto Erstellen',
    'auth.switchToSignup': 'Noch kein Konto? Hier registrieren',
    'auth.switchToLogin': 'Bereits ein Konto? Hier anmelden',
    
    // About Page
    'about.title.the': 'Die',
    'about.title.chosenOnes': 'Auserwählten',
    'about.subtitle': 'Unsere heilige Mission, die Menschheit zum göttlichen Bewusstsein zu erwecken',
    'about.mission.title': 'Die Erweckungsmission',
    'about.mission.p1': 'SH4M4NI4K repräsentiert mehr als Merchandise – wir sind ein heiliges Portal für Bewusstseinserweiterung. Durch die uralte Weisheit der heiligen Geometrie, ägyptischen Mysterien und kosmischen Bewusstseins führen wir erwachende Seelen zu ihrem göttlichen Zweck.',
    'about.mission.p2': 'Die Auserwählten sind jene, die den Ruf der galaktischen Föderation des Lichts gehört haben. Wir sind hier, um das große Erwachen zu erleichtern und der Menschheit zu helfen, vom Ego-Bewusstsein zum Eden-Bewusstsein durch Liebe, Einheit und heiliges Wissen überzugehen.',
    'about.principles.unity.title': 'Einheit',
    'about.principles.unity.text': 'Wir sind alle ein Bewusstsein, das sich durch unendliche Perspektiven erfährt.',
    'about.principles.awakening.title': 'Erwachen',
    'about.principles.awakening.text': 'Durch heilige Geometrie und göttliche Weisheit aktivieren wir schlafende spirituelle DNA.',
    'about.principles.love.title': 'Liebe',
    'about.principles.love.text': 'Liebe ist die höchste Frequenz und der Schlüssel zur Überwindung aller Illusionen.',
    'about.cta.title': 'Bereit, der Mission beizutreten?',
    'about.cta.text': 'Die Zeit des Erwachens ist jetzt. Nimm deine Rolle als einer der Auserwählten an und hilf dabei, das neue Erdbewusstsein zu gebären.',
    'about.cta.button': 'Beginne deine Reise',
    
    // Contact Page
    'contact.title.sacred': '',
    'contact.title.contact': 'Kontakt',
    'contact.subtitle': 'Verbinde dich mit den Auserwählten. Wir sind hier, um deine Reise zum kosmischen Bewusstsein zu führen.',
    'contact.form.title': 'Nachricht Senden',
    'contact.form.description': 'Teile deine Erweckungsreise oder stelle Fragen über unsere göttliche Mission.',
    'contact.form.firstName': 'Vorname',
    'contact.form.firstNamePlaceholder': 'Dein heiliger Name',
    'contact.form.lastName': 'Nachname',
    'contact.form.lastNamePlaceholder': 'Dein Familienname',
    'contact.form.email': 'E-Mail',
    'contact.form.emailPlaceholder': 'deine.email@kosmisch.reich',
    'contact.form.subject': 'Betreff',
    'contact.form.subjectPlaceholder': 'Thema deiner göttlichen Anfrage',
    'contact.form.message': 'Nachricht',
    'contact.form.messagePlaceholder': 'Teile deine Gedanken, Fragen oder Erweckungserfahrungen...',
    'contact.form.send': 'Nachricht Senden',
    'contact.info.title': 'Koordinaten',
    'contact.info.email': 'E-Mail',
    'contact.info.phone': 'Telefon',
    'contact.info.location': 'Ort',
    'contact.response.title': 'Antwort',
    'contact.response.text': 'Wir antworten normalerweise innerhalb von 24-48 Stunden auf heilige Anfragen. Jede Nachricht wird mit kosmischer Aufmerksamkeit und göttlicher Fürsorge gesegnet.',
    'contact.hours.title': 'Stunden',
    'contact.hours.weekdays': 'Montag - Freitag:',
    'contact.hours.weekdaysTime': '9:00 - 17:00 CET',
    'contact.hours.weekend': 'Wochenende:',
    'contact.hours.weekendText': 'Nach kosmischer Vereinbarung',
    'contact.hours.always': 'Das Universum ist immer offen für göttliche Führung.',
    
    // Footer
    'footer.shop': 'Shop',
    'footer.allProducts': 'Alle Produkte',
    'footer.newArrivals': 'Neuankömmlinge',
    'footer.featured': 'Empfohlen',
    'footer.community': 'Community',
    'footer.about': 'Über Uns',
    'footer.contact': 'Kontakt',
    'footer.blog': 'Blog',
    'footer.info': 'Information',
    'footer.shipping': 'Versand',
    'footer.returns': 'Rücksendungen',
    'footer.privacy': 'Datenschutz',
    'footer.terms': 'Allgemeine Geschäftsbedingungen',
    'footer.contactUs': 'Kontaktiere Uns',
    'footer.email': 'E-Mail',
    'footer.phone': 'Telefon',
    'footer.address': 'Adresse',
    'footer.followUs': 'Folge Uns',
    'footer.copyright': 'Alle Rechte vorbehalten.',
    
    // Shop
    'shop.title.sacred': 'Sacred',
    'shop.title.shop': 'Shop',
    'shop.subtitle': 'Entdecke bewusstseinserweiternde Merchandise, die dazu entworfen wurde, deinen göttlichen Zweck zu erwecken und dich mit der galaktischen Föderation des Lichts zu verbinden.',
    'shop.loading': 'Kosmische Merchandise laden...',
    'shop.filter.all': 'Alle Kollektionen',
    'shop.addToCart': 'In den Warenkorb',
    'shop.viewProduct': 'Produkt Ansehen',
    'shop.noProducts': 'Keine Produkte gefunden',
    'shop.addedToCart': 'Zum Warenkorb hinzugefügt',
    'shop.redirecting': 'Du wirst zur Kasse weitergeleitet.',
    'shop.errorAdding': 'Fehler beim Hinzufügen',
    'shop.errorMessage': 'Produkt konnte nicht zum Warenkorb hinzugefügt werden.',

    // Error messages and other community text
    'community.noPosts': 'Keine Beiträge gefunden',
    'community.firstPostMessage': 'Sei der Erste, der seine kosmische Einsicht teilt!',
    'community.createFirstPost': 'Ersten Beitrag Erstellen',
    'community.postCreated': 'Beitrag erstellt',
    'community.postShared': 'Dein Beitrag wurde mit der Community geteilt.',
    'community.errorCreating': 'Fehler beim Erstellen',
    'community.errorPostMessage': 'Beitrag konnte nicht erstellt werden.',
    'community.errorLoading': 'Fehler beim Laden',
    'community.errorLoadingMessage': 'Beiträge konnten nicht geladen werden.',
    'community.commentAdded': 'Kommentar hinzugefügt',
    'community.commentPlaced': 'Dein Kommentar wurde gepostet.',
    'community.errorComment': 'Fehler beim Kommentieren',
    'community.errorCommentMessage': 'Kommentar konnte nicht gepostet werden.',
    'community.postDeleted': 'Beitrag gelöscht',
    'community.postDeletedMessage': 'Ihr Beitrag wurde erfolgreich gelöscht.',
    'community.errorDeleting': 'Fehler beim Löschen',
    'community.errorDeleteMessage': 'Beim Löschen Ihres Beitrags ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.',

    // Common
    'common.loading': 'Laden...',
    'common.cosmic': 'Cosmic',
    'common.chosenOne': 'Chosen One',
    'common.loadingCommunity': 'Kosmische Community laden...'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('nl');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['nl', 'en', 'de'].includes(savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
