// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkxtugdsmfiwqgxmxzyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZreHR1Z2RzbWZpd3FneG14enlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NjE1MDAsImV4cCI6MjA2ODQzNzUwMH0.xEG0C0m2Oz_QbysjeFJVo0I08_zb9LgQ4N6WKwMFYlM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});